package echangole.com.retrofitsample;

import com.google.gson.annotations.SerializedName;

public class Post
{
    @SerializedName("userId")
    private int UserId;
    private Integer id;//Generated by  retrofit
    private String title;
    @SerializedName("body")
    private String text;

    public Post(int userId, String title, String text) {
        UserId = userId;
        this.title = title;
        this.text = text;
    }

    public int getUserId() {
        return UserId;
    }

    public int getId() {
        return id;
    }

    public String getTitle() {
        return title;
    }

    public String getText() {
        return text;
    }



}
